name: "Semgrep"

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run:
    if: ${{ github.actor != 'dependabot[bot]' }}

    name: "Run"
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v3

      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
